# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
#         node-version: [10.x, 12.x, 14.x, 15.x]
#         mongodb-version: [4.0, 4.2, 4.4]
        node-version: [15.x]
        mongodb-version: [4.4]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: npm ci && npm i -g projectz badges
#     - run: npm i -g projectz badges
    - run: npm run build --if-present
    - run: npm run test:coverage
      
    - run: cat ./coverage/lcov.info
    - run: cat ${{ github.workspace }}/coverage/lcov.info
    - run: ls -al ${{ github.workspace }}/coverage
    - run: ls -al ${{ github.workspace }}
      
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: ${{ github.workspace }}/coverage/lcov.info
      
#   codacy-coverage-reporter:
#     runs-on: ubuntu-latest
#     name: codacy-coverage-reporter
#     steps:
#       - uses: actions/checkout@master
#       - name: Run codacy-coverage-reporter
#         uses: codacy/codacy-coverage-reporter-action@master
#         with:
#           project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
#           coverage-reports: cobertura.xml
