# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        mongodb-version: [4.0, 4.2, 4.4]
#         node-version: [15.x]
#         mongodb-version: [4.4]

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: npm ci && npm i -g projectz badges
    - run: npm run build --if-present
    - run: npm run test:coverage

    - name: Run codacy-coverage-reporter
      if: (matrix.node-version == '15.x' && matrix.mongodb-version == 4.4)
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage/lcov.info

    - if: (matrix.node-version == '15.x' && matrix.mongodb-version == 4.4)
      uses: actions/upload-artifact@v2
      with:
        name: coverage-file
        path: ${{ github.workspace }}/coverage/lcov.info
